version: '2'
services:
  rabbit_A:
    image: rabbitmq:3.8.3-management
    hostname: rabbit_A
    ports:
      - 5672:5672 #集群内部访问的端口
      - 15672:15672 #外部访问的端口
    environment:
      - RABBITMQ_DEFAULT_USER=guest #用户名
      - RABBITMQ_DEFAULT_PASS=guest #密码

  rabbit_B:
    image: rabbitmq:3.8.3-management
    hostname: rabbit_B
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit_A
      - RAM_NODE=true
    links:
      - rabbit_A

  rabbit_C:
    image: rabbitmq:3.8.3-management
    hostname: rabbit_c
    ports:
      - 5674:5672
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit1
    links:
      - rabbit_A
      - rabbit_B
